# Code to compute R0 from specially-run simulations, Rebecca Mancy, 2021-06-24
rm(list=ls())

library(ggplot2)
library(plyr)

library(dplyr)
library(rgdal)
library(rgeos)

source("Style_Sheet.R")

setwd("~/Developer/Serengeti_Rabies/")
## ff <- "/Volumes/SimOutput01/Rabies_Sim_Output/"
ff <- "~/Developer/Serengeti_Rabies/java_output/"
max_days <- 5112
# We are interested in the 10k runs for which introductions occurred proportional to cell dog density and
#    endogenous transmission was not allowed. These can be used to compute a "dog-centric R0", corresponding
#    to the definition of R0 as the "expected number of secondary cases directly generated by one case
#    in a fully susceptible population".
# It is "expected" in the sense that we initiate choosing a dog at random in the population
# Strictly speaking, it is the "expected number of transmissions", not cases (beacuse there is the possibility of an exposed indiviudal dying)
# The population is fully susceptible in this set of runs by the way it is set up, and because we only simulate
#     a single round of transmission.
# The computation of R0 is thus based on the variable nTransmissions.
# 
folder <- "Round3_R0_CALC_1000"
sim_output <- read.csv(file = paste0(ff,folder,"/output_files/epi_outcomes_001_10000.csv"))
nrow(sim_output)
sim_output <- subset(sim_output, nAbandonments>=1) # Case 0 died as exposed ... 
nrow(sim_output)
compile_data <- F

if(compile_data) {
  
  #head(sim_output)
  ggplot(sim_output, aes(x=nTransmissions)) + geom_histogram() + scale_x_sqrt()
  ggplot(sim_output, aes(x=nDogsIntroducedCell)) + geom_histogram()
  
  sim_output$half <- ifelse(sim_output$lastCase <= (max_days/2), "First","Second")
  ggplot(sim_output, aes(x=half, y=nTransmissions)) + geom_boxplot() + scale_y_sqrt()
  ggplot(sim_output, aes(x=half, y=nDogsIntroducedCell)) + geom_boxplot() + scale_y_sqrt()
  ggplot(sim_output, aes(x=half, y=nBiteEvents)) + geom_boxplot() + scale_y_sqrt()
  
  ddply(sim_output, .(half), summarise, meanTransmissions=mean(sqrt(nTransmissions)), meanBites = mean(sqrt(nBiteEvents)), ninetyTransmissions = quantile(nTransmissions, 0.90))
  dim(sim_output)
  
  #ggplot(sim_output, aes(x=lastCase, y=nTransmissions)) + geom_point(alpha = 0.2) + scale_y_sqrt()
  # Plot R0 as a function of dog density, with logged and sqrt scales
  ggplot(sim_output, aes(x=nDogsIntroducedCell, y=nTransmissions)) + geom_point(alpha = 0.2) + scale_y_sqrt() + scale_x_log10() + geom_smooth()
  names(sim_output)
  
  # Group by popID ... Mmm, this doesn't exist in the summary file, so need to loop over all individual files
  ## R0_by_pop <- ddply(sim_output, .(popID), summarise, meanTransmissions = mean(nTransmissions), meanBites = mean(nBiteEvents))
  nReps <- 10000
  col_names <- c("popID","dogCount","dogDensityK","dayInfectious","x_coord","y_coord","nDistinctDogs","nTransmissions","nAbandonments","Th","Td")
  summary_output <- data.frame(matrix(, nrow=nReps, ncol=length(col_names)))
  colnames(summary_output) <- col_names
  for(rep in 1:nReps) {
    print(rep)
    c_dat <- read.csv(file = paste0(ff,folder,"/output_files/", folder, "_sim_cases_", sprintf(rep, fmt = "%03.0f"), ".csv"))
    summary_output[rep,] <- c_dat[1,col_names]
  }
  saveRDS(summary_output, file = paste0(ff,folder,"/postprocessing/Summary_Output.rda"))
}
summary_output <- readRDS(paste0(ff,folder,"/postprocessing/Summary_Output.rda"))
names(sim_output)
names(summary_output)

mean(sim_output$nTransmissions) # This is R0
hist(sim_output$nTransmissions)
summary(sim_output$nTransmissions)
median(sim_output$nTransmissions)
mean(summary_output$nTransmissions, na.rm=T) # Also R0
mean(summary_output$nDistinctDogs, na.rm=T) # Number of distinct dogs bitten # 2.51026

mean(sim_output$nBiteEvents)
mean(sim_output$nDistinctE)
mean(sim_output$nDistinctV)
mean(sim_output$nDistinctS*.49) # This is lower than nTransmissions because sometimes the same dog can be
# bitten multiple times ... 
mean(sim_output$nDistinctS)
#  However, nDistinctS is the upper bound on R0, i.e. R0 < nDistinctS

# Plot the distribution of R values
g <- ggplot(summary_output, aes(nTransmissions)) + 
  geom_histogram(aes(y=after_stat(density)), alpha = 0.5, binwidth = 1) +
  #scale_x_continuous(expression('R'[0])) +
  scale_x_continuous(expression(nu)) +
  ss; g

# # ----------------------------------- Prob not needed from here down ----------------------------------
# 
# #summary(sim_output)
# mean(sim_output$nTransmissions + sim_output$nReinfections)
# 
# summary_output <- readRDS(file = paste0(ff,folder,"/postprocessing/Summary_Output.rda"))
# summary(summary_output)
# hist(summary_output$nTransmissions)
# by_pop <- ddply(summary_output, .(popID), summarise, meanTransmissions = mean(nTransmissions), meanDistinctDogs = mean(nDistinctDogs), nRecords = length(popID))
# dim(by_pop)
# hist(by_pop$meanTransmissions)
# 
# 
# load("data/grd_1000.rda")
# #library(rgdal)
# #SD2000 <- readOGR(dsn = "~/Documents/GitHub/Serengeti_Rabies/data/grd_1000.rda")
# names(grd.1000)
# grd.1000$popID[1:10]
# 
# test <- left_join(grd.1000@data, by_pop, by=c("popID", "popID"))
# head(test)
# hist(test$meanTransmissions)
# test$id <- as.character(test$popID)
# #grd.1000@data <- test
# #if (!require(gpclib)) install.packages("gpclib", type="source")
# #library(gpclib)
# #gpclibPermit()
# grd.1000.df <- fortify(grd.1000, region = "popID")
# grd.1000.df <- left_join(grd.1000.df, test, by=c("id","id"))
# 
# # Map of the number of record by area (to show sampling)
# map <- ggplot(data = grd.1000.df, aes(x = long, y = lat, group = group)) + 
#   geom_path() +
#   geom_polygon(aes(fill = nRecords)) +
#   scale_fill_gradient2(midpoint = 1, low = "blue", high = "red") +
#   coord_equal() + 
#   theme_light()
# map
# 
# # Map of the number of transmissions by area
# map <- ggplot(data = grd.1000.df, aes(x = long, y = lat, group = group)) + 
#   geom_path() +
#   geom_polygon(aes(fill = sqrt(meanTransmissions))) +
#   scale_fill_gradient2(midpoint = 1, low = "blue", high = "red") +
#   coord_equal() + 
#   theme_light()
# map
# 
# # Histogram by grid cell
# g_hist <- ggplot(data=by_pop, aes(x=meanTransmissions)) + 
#   geom_histogram(binwidth = 1) + 
#   geom_vline(xintercept = mean(by_pop$meanTransmissions, na.rm=T), colour = "red", linetype = 2) +
#   annotate(geom = "text", x = mean(by_pop$meanTransmissions, na.rm=T), y = 1100, label = sprintf("%1.3f", mean(by_pop$meanTransmissions, na.rm=T))) +
#   ggtitle("Distribution of mean number of transmissions per grid cell") +
#   theme_light(); g_hist
# ggsave(plot = g_hist, filename = "Hist_Transmissions_Per_Cell.pdf", path = "figs", width = 15, height = 10, units = "cm")
# 
# # Histogram by dog
# g_hist <- ggplot(data=summary_output, aes(x=nTransmissions)) + 
#   geom_histogram(binwidth = 1) + 
#   geom_vline(xintercept = mean(summary_output$nTransmissions, na.rm=T), colour = "red", linetype = 2) +
#   annotate(geom = "text", x = mean(summary_output$nTransmissions, na.rm=T), y = 6500, label = sprintf("%1.3f", mean(summary_output$nTransmissions, na.rm=T))) +
#   ggtitle("Distribution of number of transmissions per infectious dog") +
#   theme_light(); g_hist
# ggsave(plot = g_hist, filename = "Hist_Transmissions_Per_Dog.pdf", path = "figs", width = 15, height = 10, units = "cm")
# 
# # Relationship between grid cell R0 and density
# g_scatter <- ggplot(data=subset(by_pop, meanTransmissions<100), aes(x=nRecords, y=meanTransmissions)) + 
#   geom_jitter(alpha = 0.4, size=0.7, shape = 1) +
#   geom_smooth() + 
#   scale_x_continuous("Number of incursions in cell (proportional to density)") +
#   scale_y_continuous("Mean transmissions (grid cell R0)") +
#   theme_light(); g_scatter
# ggsave(plot = g_scatter, filename = "Scatter_Transmissions_On_Density.pdf", path = "figs", width = 15, height = 10, units = "cm")
# 
# ## 
# 
# mod <- lm(nTransmissions ~ poly(nDogsIntroducedCell,2), data = sim_output)
# summary(mod)
# 
# mod <- lm(nTransmissions ~ I(nDogsIntroducedCell) + I(nDogsIntroducedCell^2), data = sim_output)
# summary(mod)
# 
# summary(sim_output)
# 
# # All bite events ...
# mean(sim_output$nBiteEvents - 1)
# mean(sim_output$nTransmissions + sim_output$nFailedTransmissions + sim_output$nReinfections + sim_output$nAbandonments - 1)
# mean(sim_output$nTransmissions + sim_output$nFailedTransmissions + sim_output$nReinfections - 1) # removing abandonments makes a big difference
# mean(sim_output$nTransmissions + sim_output$nFailedTransmissions +                           sim_output$nAbandonments - 1) # removing reinfections doesn't affect things much
# mean(sim_output$nTransmissions                                   + sim_output$nReinfections + sim_output$nAbandonments - 1) # removing failed transmissions makes a big difference
# ggplot(sim_output, aes(x=nBiteEvents, y=(nTransmissions + nFailedTransmissions + nReinfections + nAbandonments))) + geom_point(alpha=0.2) + geom_abline(slope=1, intercept = 0)
# 
# dim(subset(sim_output, nAbandonments==0))
# subset(sim_output, nAbandonments==0)
# head(sim_output)
