# Version updated in February 2022

# Prior to running this code, the Case_List generated by Make_Case_List.R needs to be 
#   processed using the Java PostProcessor

rm(list=ls()); options(stringsAsFactors = F)

library(lubridate)
library(plyr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(reshape2)
library(fitdistrplus)
source("R/computeDDBounds.R")

# Process_ABC.R
ff_output = "output/abc_criteria/"
ff_input = "java_output/"
start.date <- as.Date('2002-01-01', tz = "GMT")
end.date <- as.Date('2015-12-31')
mths <- seq(start.date, end.date, by="month")
qrts <- seq(start.date, end.date, by="quarter")
month.vec.dots <- format(seq(start.date, end.date, by="month"), format = "%Y.%m.%d") #; year.vec <- as.character(seq(start.date, end.date, by="year"))
month.vec <- format(seq(start.date, end.date, by="month"), format = "%Y-%m-%d") #; year.vec <- as.character(seq(start.date, end.date, by="year"))
f.cases.per.month.bounds <- "carnivore_cases_per_month_bounds.rda" 
f.shift.bounds <- "shift_bounds.rda"

source("Style_Sheet.R")

# Compute bounds for acceptance/rejection

# ---------------- Cases per month distribution ---------------------
source("R/computeCasesPerMonthBounds.R")
source("R/computeCasesPerMonthOutside.R")
# Compute bounds on cases.per.month histogram for acceptance, including all carnivores
paramMinMax.str <- "001_001"
experiment.id <- "Round0_1000"
mt <- read.csv(paste0(ff_input, experiment.id, "/postprocessing/monthlyTally_", paramMinMax.str, ".csv")) # To obtain "data"
# Check total number of cases in data
sum(mt[1,1:168])
c.cases.per.month <- as.numeric(mt[1,1:(ncol(mt)-1)]); rm(mt)
c.cases.per.month.hist.breaks <- c(seq(0,250,by=5),100000)
c.j.cases.per.month.hist.breaks <- c.cases.per.month.hist.breaks[2:length(c.cases.per.month.hist.breaks)] # Java-style breaks for use in post-processing
c.cases.per.month.bounds <- computeCasesPerMonthBounds(c.cases.per.month, ci = 0.999, hist.breaks = c.cases.per.month.hist.breaks, n.draws = 100000)
# NB: This plots using the "mids" of R's hist as the x-axis
c.cases.per.month.outside.data <- computeCasesPerMonthOutside(c.cases.per.month.bounds, c.cases.per.month, c.cases.per.month.hist.breaks, do.plot=T)
c.cases.per.month <- data.frame(month = seq(start.date, end.date, by = "month"), cases = c.cases.per.month)
saveRDS(c.cases.per.month.bounds, file = paste0(ff_output, "c_cases_per_month_bounds.rda"))
saveRDS(c.cases.per.month.hist.breaks, file = paste0(ff_output, "c_cases_per_month_hist_breaks.rda"))
saveRDS(c.j.cases.per.month.hist.breaks, file = paste0(ff_output, "c_j_cases_per_month_hist_breaks.rda"))
saveRDS(c.cases.per.month, file = paste0(ff_output, "c_cases_per_month.rda"))

# -------------------------- Shift bounds -----------------------------
source("R/computeShiftBounds.R")
source("R/computeShiftHistogramPointsOutside.R")
# For this criterion, a couple of steps need to occur:
#   1. Run Java code in PostProcessor, using d_cases_java.csv as comparison to obtain standardised log densities at case locations, 
#      based on metapopulation with buffer, and output as densitiesData.csv in Round0_1000/postprocessor 
#      (this code may crash because it is intended to also read in simulated data that don't exist; it also overwrites other files).
#   2. Use the output of the file densitiesData.csv to compute the shift information


d.cases.java.reallocated <- read.csv("output/d_cases_java_deid.csv")
# Step 1: done in Java
# Step 2
rabid.dogs <- read.csv(paste0(ff_input, "/Round0_1000/postprocessing/densitiesData.csv"))
rabid.dogs$stdTCDensity1000 <- rabid.dogs$sld1000
nrow(rabid.dogs)
nrow(subset(rabid.dogs, !is.na(stdTCDensity1000)))

# Compute bounds on "shift" histogram for acceptance (using standardised density)
dog.densities <- rabid.dogs$sld1000
hist(dog.densities, breaks=seq(-2.5,4,by=0.01))
density.breaks.by <- 0.25
dog.density.hist.breaks <- seq(-2.25, 4, by=density.breaks.by)
j.dog.density.hist.breaks <- dog.density.hist.breaks[2:length(dog.density.hist.breaks)]
shift.bounds <- computeShiftBounds(dog.densities, ci = 1, hist.breaks = dog.density.hist.breaks, n.draws = 100000, n.to.draw = nrow(rabid.dogs), sd.jitter = 0.05)
dog.densities.hist <- hist(dog.densities, breaks=dog.density.hist.breaks, plot=F)
dog.density.hist.mids <- dog.densities.hist$mids
shift.histogram.points.outside <- computeShiftHistogramPointsOutside(shift.bounds, densities = dog.densities.hist$density, hist.mids = dog.densities.hist$mids, dog.density.hist.breaks, do.plot=T); shift.histogram.points.outside
saveRDS(shift.bounds, file = paste0(ff_output, "shift_bounds.rda"))
saveRDS(dog.density.hist.breaks, file = paste0(ff_output, "dog_density_hist_breaks.rda"))
saveRDS(dog.densities, file = paste0(ff_output, "dog_densities.rda"))
saveRDS(dog.densities.hist, file = paste0(ff_output, "dog_densities_hist.rda"))
saveRDS(dog.density.hist.mids, file = paste0(ff_output, "dog_density_hist_mids.rda"))
saveRDS(density.breaks.by, file = paste0(ff_output, "density_breaks_by.rda"))
saveRDS(j.dog.density.hist.breaks, file = paste0(ff_output, "j_dog_density_hist_breaks.rda")) 

# -------------------------- Animals bitten bounds -------------------------
# Load up information on cases
source("R/computeDDPointsOutside.R")
case_list_rda <- readRDS(file = "output/matching_data_caselist_deid.rda")
dim(case_list_rda)
summary(case_list_rda$Animals.bitten) # mean 2.035, max 82
summary(case_list_rda$Dogs.bitten) # mean 1.818, max 72
quantile(case_list_rda$Dogs.bitten, probs = 0.99) # 22
# We bootstrap from this, rather than fitting an arbitrary distribution

dd.hist.breaks <- c(seq(0,82),10000)
j.dd.hist.breaks <- dd.hist.breaks[2:length(dd.hist.breaks)]
dd.bounds <- computeDDBounds(nBites = case_list_rda$Animals.bitten, ci = 0.999, hist.breaks = dd.hist.breaks, n.draws = 100000, n.to.draw = nrow(case_list_rda), sd.jitter = 0.0)
dim(dd.bounds)
# Correct for zeros up to 82, and set lower bound to zero after 15
dd.bounds$ub <- ifelse(dd.bounds$ub < 1/nrow(case_list_rda) & dd.bounds$cases < 82 | dd.bounds$cases >5000, 0.00214669, dd.bounds$ub)
dd.bounds$lb <- ifelse(dd.bounds$lb > 0 & dd.bounds$cases > 15, 0, dd.bounds$lb)
# Note that the 'cases==0.5' means 0 bites here, so the max here is 82, then it's 82+. Done this way because that's how they are aggregated in Postprocessor in Java

dd.hist <- hist(case_list_rda$Animals.bitten, dd.hist.breaks)$counts
dd.hist.mids <- hist(case_list_rda$Animals.bitten, dd.hist.breaks)$mids
c.dd.outside.data <- computeDDPointsOutside(dd.bounds = dd.bounds, sim.dd = dd.hist, hist.breaks = dd.hist.breaks[2:length(dd.hist.breaks)], hist.breaks.mids = dd.hist.mids, do.plot = T)

saveRDS(dd.bounds, file = paste0(ff_output, "dd_bounds.rda"))
saveRDS(dd.hist.breaks, file = paste0(ff_output, "dd_hist_breaks.rda"))
saveRDS(j.dd.hist.breaks, file = paste0(ff_output, "j_dd_hist_breaks.rda"))
saveRDS(dd.hist.mids, file = paste0(ff_output, "dd_hist_mids.rda"))
saveRDS(dd.hist, file = paste0(ff_output, "dd_hist.rda"))


