# Version updated on 24 June 2021

library(lubridate)
library(plyr)
library(ggplot2)
library(reshape2)
#library(kSamples)
#library(SimInfMakeData)
library(fitdistrplus)
#library("plot3D")

rm(list=ls()); options(stringsAsFactors = F)

source("R/computeCasesPerMonthOutside.R")
source("R/computeShiftHistogramPointsOutside.R")

# Function to plot density histograms
p.dh <- function ( dh, abc, ymax, dog.density.hist.breaks, freq=T ) {
  dh$abc.var <- abc$abc.var; dh$densityDependence <- abc$densityDependence
  dh$ar <- ifelse (dh$Param == "data", "Data", ifelse(abc$abc.var > alfa, "Accepted", "Rejected"))
  colnames(dh)[1:(length(j.dog.density.hist.breaks))] <- j.dog.density.hist.breaks
  shift.bounds$breaks <- j.dog.density.hist.breaks
  #dh <- dh[,2:ncol(dh)] # remove the -5 column that contains "empty" cells
  m.dh <- melt(dh, id.vars = c("Param","ar","abc.var","densityDependence")); m.dh$variable <- as.numeric(as.character(m.dh$variable)) #; m.mh$variable <- ifelse(m.mh$variable == 100000, 405, m.mh$variable)
  if (freq) {
    p.dh <- ggplot(subset(m.dh, abc.var > alfa), aes(x=variable, y=value)) + geom_line(aes(group=Param, colour=densityDependence), alpha=0.2) +
      geom_line(data=subset(m.dh, Param=="data"), aes(x=variable, y=value), colour = "red") +
      scale_colour_gradient(low = sc.colours$dark.navy, high = sc.colours$orange, limits = c(0,1)) + xlab("Standardised dog density at case location") + ylab("Case frequency") + theme_light(); p.dh
  } else { # densities
    dh.mat <- as.matrix(dh[,1:length(j.dog.density.hist.breaks)])
    dh.mat[,1] <- 0 # all zeros in first column; do this before computing sums
    dh.mat.densities <- (1/density.breaks.by) * dh.mat / rowSums(dh.mat)
    dh.densities <- as.data.frame(dh.mat.densities)
    dh.densities <- cbind(dh.densities, Param=dh$Param, ar=dh$ar, abc.var=dh$abc.var, densityDependence=dh$densityDependence)
    m.dh <- melt(dh.densities, id.vars = c("Param","ar","abc.var","densityDependence")); m.dh$variable <- as.numeric(as.character(m.dh$variable)) #; m.mh$variable <- ifelse(m.mh$variable == 100000, 405, m.mh$variable)
    p.dh <- ggplot(subset(m.dh, abc.var > alfa), aes(x=variable, y=value)) +
      geom_line(data=shift.bounds, aes(x=breaks, y=ub), colour=sc.colours$blue, lty=3, size=0.3) +
      geom_line(aes(group=Param, colour=densityDependence), alpha=0.2) +
      geom_line(data=subset(m.dh, Param=="data"), aes(x=variable, y=value), colour = "red") +
      geom_line(data=shift.bounds, aes(x=breaks, y=lb), colour=sc.colours$blue, lty=3, size=0.3) +
      scale_colour_gradient(low = sc.colours$dark.navy, high = sc.colours$orange, limits = c(0,1)) + xlab("Standardised dog density at case location") + ylab("Case density") + theme_light(); p.dh
  }
  return(p.dh)
}

# Process_ABC.R
ff <- "/Volumes/SimOutput01/Rabies_Sim_Output/abc_criteria/"
start.date <- as.Date('2002-01-01')
end.date <- as.Date('2015-12-31')
mths <- seq(start.date, end.date, by="month")
qrts <- seq(start.date, end.date, by="quarter")
month.vec.dots <- format(seq(start.date, end.date, by="month"), format = "%Y.%m.%d") #; year.vec <- as.character(seq(start.date, end.date, by="year"))
month.vec <- format(seq(start.date, end.date, by="month"), format = "%Y-%m-%d") #; year.vec <- as.character(seq(start.date, end.date, by="year"))
detection.percentage <- 100
f.cases.per.month.bounds <- "c_cases_per_month_bounds.rda"
f.shift.bounds <- "shift_bounds.rda"
animal.type <- "carnivores"

source("Style_Sheet.R")

# ---- Load up bounds for acceptance/rejection ----
cases.per.month.bounds <- readRDS(paste0(ff, f.cases.per.month.bounds))
cases.per.month.hist.breaks <- readRDS(paste0(ff, "c_cases_per_month_hist_breaks.rda"))
cases.per.month <- readRDS(paste0(ff, "c_cases_per_month.rda"))
shift.bounds <- readRDS(paste0(ff, "shift_bounds.rda"))
dog.densities.hist <- readRDS(paste0(ff, "dog_densities_hist.rda"))
dog.density.hist.breaks <- readRDS(paste0(ff, "dog_density_hist_breaks.rda"))
dog.density.hist.mids <- readRDS(paste0(ff, "dog_density_hist_mids.rda"))
j.dog.density.hist.breaks <- readRDS(paste0(ff, "j_dog_density_hist_breaks.rda"))
density.breaks.by <- readRDS(paste0(ff, "density_breaks_by.rda"))

# ---- Post-processing ----
mean.density.period <- 22.43698

# Set stuff up
ff <- "/Volumes/SimOutput01/Rabies_Sim_Output/"
alfa <- 0.01
model <- "Round2"; 
spatial.scale <- "all";
paramMinMax <- c(1,3400)
load.only <- F
param.ids.str <- sprintf("%.3d", seq(paramMinMax[1], paramMinMax[2]))
paramMinMax.str <- paste(sprintf("%.3d", paramMinMax),collapse="_")

date.format <- "%Y-%m-%d"

postprocessing.folder <- paste0("postprocessing")
experiment.id <- paste0(model, "_", spatial.scale, "/", postprocessing.folder)

# Read in summary files generated by Java code
abc <- read.csv(paste0(ff, experiment.id, "/abc_", paramMinMax.str, ".csv")) # This is the file produced by the post-processing step in Java
mt <- read.csv(paste0(ff, experiment.id, "/monthlyTally_", paramMinMax.str, ".csv"))
mh <- read.csv(paste0(ff, experiment.id, "/monthlyHistogram_", paramMinMax.str, ".csv"))
#mc1000 <- read.csv(paste0(ff, experiment.id, "/monthlyMaxCases1000_", paramMinMax.str,".csv")); mc1000$Param <- mc1000$X; mc1000$X <- NULL
dh1000 <- read.csv(paste0(ff, experiment.id, "/densityHistogram1000_", paramMinMax.str, ".csv"))
outputs <- read.csv(paste0(ff, model, "_", spatial.scale, "/", "/output_files/epi_outcomes_", paramMinMax.str,".csv"))
#outputs <- outputs[1:654,]
output.cols <- c("nDemographicEvents","nBiteEvents","nTransmissions","nAbandonments","nBitesE","nBitesV","nFailedTransmissions",
                 "nReinfections","nDistinctS","nDistinctE","nDistinctV","nDiedE")
abc <- cbind(abc, rbind(rep(-1, length(output.cols)), outputs[output.cols]))

# # These required only for plotting
ddh <- read.csv(paste0(ff, experiment.id, "/distinctDogs_", paramMinMax.str, ".csv"))

# Some summaries for checking
head(abc); dim(abc)
summary(abc[2:nrow(abc),])
table(abc$stoppedEarly)


# ------------------------- COMPUTE ABC STATS ----------------------------

if (load.only) {
  load(paste0(paste0(ff, experiment.id, "/abc_stats_", paramMinMax.str, ".rda")))
} else {
  # Compute ABC statistics (Anderson-Darling, not easily available in Java)
  abc$Proportion.noncontributors <- abc$numNonContributors / abc$numDetectableDogs
  abc$Proportion.superspreaders <- abc$numSuperspreaders / abc$numDetectableDogs
  
  # Cases per month falls inside ... (how many of the points are outside!)
  abc$cases.per.month.outside <- 0
  abc$shift.histogram.points.outside <- 0
  
  # Convert monthly tally to a version without Param to use in matching
  mt.num <- mt; mt.num$Param <- NULL
  
  for (rr in 1:nrow(abc)) {
    # Compute test statistics and add to abc data.frame
    if (rr > 1){
      print(rr)
      # Cases per month distribution
      # if (ncol(mh)!=(length(cases.per.month.hist.breaks))) stop("The number of columns in mh is not equal to the number of breaks to be used.")
      abc$cases.per.month.outside[rr] <- computeCasesPerMonthOutside(cases.per.month.bounds, as.numeric(mt.num[rr,]), cases.per.month.hist.breaks, do.plot=F)
      #title(paste0("rr: ", rr, "\nNum outside: ", abc$cases.per.month.outside[rr]))
      
      # Density - shift - distribution
      if (ncol(dh1000)!=(length(dog.density.hist.breaks))) stop("The number of columns in dh1000 is not equal to the number of breaks to be used.")
      density.counts <- as.numeric(dh1000[rr,1:(length(dog.density.hist.breaks)-1)])
      density.counts[1:2] <- 0 # This is the number of cases in empty space - we ignore this
      density.relative <- (1/density.breaks.by) * density.counts / sum(density.counts)
      abc$shift.histogram.points.outside[rr] <- computeShiftHistogramPointsOutside(shift.bounds, densities = density.relative, hist.breaks = dog.density.hist.breaks, hist.mids = dog.density.hist.mids, do.plot=F)
      #if (abc$shift.histogram.points.outside[rr] < 4) {
      #  compute.shift.histogram.points.outside(shift.bounds, densities = density.relative, hist.breaks = dog.density.hist.breaks, hist.mids = dog.density.hist.mids, do.plot=T)
      #}
    }
  }
  # Some additional statistics to add in ...
  # Total number of cases and maximum number of cases per month
  for (rr in 1:nrow(mt)) {
    max <- max(mt[rr,1:(ncol(mt)-1)])
    abc$maxPerMonth[rr] <- ifelse((abc$stoppedEarly[rr]=="true" & abc$Param[rr] != "data"), -1, max)
  }
  # # Maximum number of cases per month per cell
  # for (rr in 1:nrow(mc1000)) {
  #   max <- max(mc1000[rr,1:(ncol(mc1000)-1)])
  #   abc$maxPerMonthPer1000[rr] <- ifelse((abc$stoppedEarly[rr]=="true" & abc$Param[rr] != "data"), -1, max)
  # }
  summary(abc$maxPerMonth); summary(abc$maxPerMonthPer1000); summary(abc$totalCases)
  save(abc, file=paste0(paste0(ff, experiment.id, "/abc_stats_", paramMinMax.str, ".rda")))
  
}

# Plot those that stopped early, and R0 values calculated from them
p.stoppedEarly <- ggplot(subset(abc, R0<=5 & Param!="data"), aes(x=R0)) + geom_histogram(position = "stack", aes(fill=stoppedEarly));p.stoppedEarly
min.stoppedEarly <- min(subset(abc, stoppedEarly=="true" & Param!="data")$R0)
max.not.stoppedEarly <- max(subset(abc, stoppedEarly=="false" & Param!="data")$R0)
ggsave(plot = p.stoppedEarly, title = paste0(experiment.id, "\nMin R0 stopped early = ", min.stoppedEarly,"\nMax R0 completed = ", max.not.stoppedEarly),
       filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_R0_stoppedEarly.pdf"))
# How big can an outbreak get before we stop it early?
summary(subset(abc, stoppedEarly == "false")$numDetectableDogs)
table(abc$stoppingReason)

# ---- Accept / Reject ----

table(abc$stoppedEarly)/nrow(abc)
table(cpm=abc$cases.per.month.outside, shift=abc$shift.histogram.points.outside)

# Threshold points ... (baseline 2, 4, 100)
thresh.cpm <- 2
thresh.shift <- 4
max.dd <- 100
table(abc$cases.per.month.outside <= thresh.cpm)
# Acceptance step
abc$Accepted <- (abc$cases.per.month.outside <= thresh.cpm & abc$shift.histogram.points.outside <= thresh.shift & abc$stoppingReason == "Completed" & abc$maxDD <= max.dd)
# Summarise accepted runs
table(abc$Accepted)
summary(filter(abc, Accepted)$R0)

# ------------------------- PLOTTING ----------------------------

# For plotting
abc$Accepted_Alfa <- ifelse(abc$Accepted, 0.3, 0)
abc.vars.str <- "Accepted_Alfa"
#abc.vars.str <- "all_runs"
#abc.vars.str <- c("Accepted_Alfa","all_runs")

alfa <- 0.00
# Make diagnostic plots
for ( abc.var.str in abc.vars.str ) {
  # Setup
  if (abc.var.str %in% c("all_runs","TESTBEST", "TESTBEST2")) {
    abc$abc.var <- 1 # Plot all outputs, not just accepted runs
  } else {
    abc$abc.var <- abc[,abc.var.str]
    abc$abc.var[1] <- 1 # The first row is the data ... so set "distance" (really 1-distance, i.e. probability of matching) to one
  }
  
  palette.ar2 <- c(Rejected=sc.colours$grey, Accepted=sc.colours$orange)
  palette.ar3 <- c(Data=sc.colours$bright.red, Rejected=sc.colours$grey, Accepted=sc.colours$orange)
  palette.ad2 <- c(Data=sc.colours$bright.red, Accepted=sc.colours$orange)
  
  # Compute some summary information
  meanR0Accept <- sprintf("%0.2f", mean(subset(abc, (abc.var > alfa & Param!="data"))$R0), na.rm=T)
  nAccept <- nrow(subset(abc, abc.var > alfa & Param!="data"))
  percAccept <- sprintf("%0.2f", 100* nAccept / (nrow(abc)-1))
  
  # Plot timeseries accepted and rejected
  mt$abc.var <- abc$abc.var; mt$densityDependence <- abc$densityDependence; mt$maxPerMonth <- abc$maxPerMonth; mt$ThShape <- abc$ThShape;mt$TdMean <- abc$TdMean;
  mt$incursionRate <- abc$incursionRate; mt$maxDD <- abc$maxDD
  mt$ar <- ifelse (mt$Param == "data", "Data", ifelse(abc$abc.var > alfa, "Accepted", "Rejected"))
  m.mt <- melt(mt, id.vars = c("Param", "ar","abc.var","densityDependence","maxPerMonth","ThShape","incursionRate","maxDD","TdMean")); m.mt$variable <- as.numeric(gsub("X", replacement = "", m.mt$variable)); m.mt$Month <- start.date + m.mt$variable
  ##p.ts <- ggplot(m.mt, aes(x=Month, y=value)) + geom_line(aes(group=Param, alpha=abc.var, colour=factor(abc.var>alfa))) + ylim(c(0,250)); p.ts
  ##p.ts <- ggplot(subset(m.mt, abc.var>alfa), aes(x=Month, y=value)) + geom_line(aes(group=Param, alpha=abc.var, colour=ar)) +
  ##ylim(c(0,250)) + scale_colour_manual(values = palette.ad2); p.ts
  p.ts <- ggplot(subset(m.mt, abc.var>alfa), aes(x=Month, y=value)) + geom_line(aes(group=Param, colour=densityDependence),alpha=0.3, size=0.3) +
    geom_line(data=subset(m.mt, Param=="data"), aes(x=Month, y=value), colour = "red") +
    scale_colour_gradient(low = sc.colours$dark.navy, high = sc.colours$orange, limits = c(0,1))
  if(abc.var.str!="all_runs") {maxy <- 300} else {maxy <- 1000}
  p.ts <- p.ts + ylim(c(0,maxy)) +
    theme_light();p.ts
  ggsave(plot = p.ts, title = paste0(experiment.id, " ", abc.var.str), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_ts.pdf"))
  
  p.ts <- ggplot(subset(m.mt, abc.var>alfa), aes(x=Month, y=value)) + geom_line(aes(group=Param, colour=log1p(ThShape),alpha=ThShape),  size=0.2) +
    geom_line(data=subset(m.mt, Param=="data"), aes(x=Month, y=value), colour = "red") +
    scale_colour_gradient(low = sc.colours$bright.red, high = sc.colours$blue)
  if(abc.var.str!="all_runs") {maxy <- 300} else {maxy <- 1000}
  p.ts <- p.ts + ylim(c(0,maxy));
  p.ts + theme_classic()
  ggsave(plot = p.ts, title = paste0(experiment.id, " ", abc.var.str), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_ts_Thshape.pdf"))
  
  p.ts <- ggplot(subset(m.mt, abc.var>alfa), aes(x=Month, y=value)) + geom_line(aes(group=Param, colour=log1p(TdMean),alpha=TdMean),  size=0.2) +
    geom_line(data=subset(m.mt, Param=="data"), aes(x=Month, y=value), colour = "red") +
    scale_colour_gradient(low = sc.colours$bright.red, high = sc.colours$blue)
  if(abc.var.str!="all_runs") {maxy <- 300} else {maxy <- 1000}
  p.ts <- p.ts + ylim(c(0,maxy));
  p.ts + theme_classic()
  ggsave(plot = p.ts, title = paste0(experiment.id, " ", abc.var.str), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_ts_TdMean.pdf"))
  
  #p.ts <- ggplot(subset(m.mt, abc.var>alfa & ar!="Data"), aes(x=Month, y=value)) + geom_line(aes(group=Param, colour=incursionRate, alpha=abc.var)) +
  #  geom_line(data=subset(m.mt, Param=="data"), aes(x=Month, y=value), colour = "red") +
  #  scale_colour_gradient(low = sc.colours$dark.navy, high = sc.colours$orange); p.ts + theme_classic()
  
  # # Plot cases per month histogram by accepted and rejected
  mh$abc.var <- abc$abc.var;
  mh$densityDependence <- abc$densityDependence
  mh$ar <- ifelse (mh$Param == "data", "Data", ifelse(abc$abc.var > alfa, "Accepted", "Rejected"))
  m.mh <- melt(mh, id.vars = c("Param","ar","abc.var","densityDependence")); m.mh$variable <- as.numeric(gsub("X", replacement = "", m.mh$variable)); m.mh$variable <- ifelse(m.mh$variable == 100000, 405, m.mh$variable)
  cpmb <- cbind(cases.per.month.bounds, breaks=cases.per.month.hist.breaks[2:length(cases.per.month.hist.breaks)])
  p.mh <- ggplot(subset(m.mh, abc.var > alfa), aes(x=variable, y=value)) + geom_line(aes(group=Param, colour=densityDependence), alpha = 0.2) +
    geom_line(data=subset(m.mh, Param=="data"), aes(x=variable, y=value), colour = "red") +
    geom_line(data=subset(cpmb,breaks<5000), aes(x=breaks, y=lb), colour=sc.colours$blue, lty=3, size=0.3) +
    geom_line(data=subset(cpmb,breaks<5000), aes(x=breaks, y=ub), colour=sc.colours$blue, lty=3, size=0.3) +
    ylim(c(0,100)) + scale_colour_gradient(low = sc.colours$dark.navy, high = sc.colours$orange, limits = c(0,1)) + theme_light(); p.mh 
  ggsave(plot = p.mh, title = paste0("Distribution of number of cases per month\n", experiment.id, " ", abc.var.str), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_mh.pdf"))

  # Plot the parameters in a way that gives all parameters a colour/size/axis code
  acc <- subset(abc, Accepted & stoppedEarly=="false" & Param!="data")

  p.thtd.plus <- ggplot(data=acc, aes(x=ThMean, y=TdMean)) + 
    geom_point(aes(alpha=ThShape, colour=densityDependence, size=R0, shape=maxDD>100)) +
    scale_colour_gradient(low=sc.colours$bright.blue, high=sc.colours$orange, limits = c(0,1)) + xlim(c(0,5)) + ylim(c(0,25)) + theme_light(); p.thtd.plus
  ggsave(plot = p.thtd.plus, title = paste0("ABC outcomes\n", experiment.id, " ", abc.var.str,"\nMean accepted R0 = ", meanR0Accept), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_abc_ThTd_nonfacetted.pdf"))
  
  p.facet <- ggplot(data=acc, aes(x=ThMean, y=TdMean)) + geom_point(aes(alpha=ThShape, colour=densityDependence, size=incursionRate, shape=maxDD>100)) +
    scale_colour_gradient(low=sc.colours$bright.blue, high=sc.colours$orange) + facet_grid(cases.per.month.outside ~ shift.histogram.points.outside) + xlim(c(0,5)) + ylim(c(0,25)) + theme_light()
  ggsave(plot = p.facet, title = paste0("ABC outcomes\n", experiment.id, " ", abc.var.str,"\nMean accepted R0 = ", meanR0Accept), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_abc_ThTd_facetted.pdf"))
  
  p.shift.outside <- ggplot(abc, aes(x=shift.histogram.points.outside, group=shift.histogram.points.outside, y=densityDependence)) + geom_boxplot()
  ggsave(plot = p.shift.outside, title = paste0("Shift outside\n", experiment.id, " ", abc.var.str), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_abc_shift_outside.pdf"))
  
  p.cpm.outside <- ggplot(abc, aes(x=cases.per.month.outside, group=cases.per.month.outside, y=densityDependence)) + geom_boxplot()
  ggsave(plot = p.cpm.outside, title = paste0("Cases per month outside\n", experiment.id, " ", abc.var.str,"\nMean accepted R0 = ", meanR0Accept), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_abc_cpm_outside.pdf"))
  
  # Plot distinct dogs histogram
  # ---- Superspreaders are dogs that bite more than the 99% quantile of Poisson distribution with the same mean (Jamie Lloyd-Smith) ----
  # my.lambda <- 5
  # test <- data.frame(value = rpois(n = 10000, lambda = my.lambda))
  # test <- data.frame(value = rlnorm(n = 10000, meanlog = 5, sdlog = 2))
  # mu.hat <- mean(test$value)
  # thresh <- qpois(p = 0.99, lambda = mu.hat, lower.tail = T, log.p = F)
  # test$Superspreader <- ifelse(test$value > thresh, T, F)
  # #ggplot(test, aes(x = value)) + geom_histogram(binwidth = 1, aes(fill = Superspreader)) + geom_vline(xintercept = mu.hat)
  # ggplot(test, aes(x = value)) + geom_histogram(bins = 500, aes(fill = Superspreader)) + geom_vline(xintercept = mu.hat)
  # prop.superspreader <- nrow(subset(test, Superspreader))/nrow(test)
  
  abc$Acc <- factor(abc$abc.var > alfa, levels=c("FALSE","TRUE"))
  
  # Histogram of the by-run proportion of superspreaders
  data.prop.superspreader <- abc$numSuperspreaders[1] / abc$numDetectableDogs[1]
  ### p.dd.prop <- ggplot(subset(abc, (Param!="data" & numDetectableDogs > 0 & stoppedEarly =="false")), aes(x = Prop.superspreader)) + geom_histogram(bins=20, aes(fill = abc.var > alfa)) + geom_vline(xintercept = data.prop.superspreader)
  p.dd.prop <- ggplot(subset(abc, (Param!="data" & numDetectableDogs > 0 & stoppedEarly =="false")), aes(x = Proportion.superspreaders)) + geom_histogram(breaks=seq(0,0.15, by=0.005), aes(fill = Acc)) + geom_vline(xintercept = data.prop.superspreader)
  ggsave(plot = p.dd.prop, title = paste0("Proportion of \n", experiment.id, " ", abc.var.str,"\nProportion superspreaders (data) = ", data.prop.superspreader), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_abc_proportion_superspreaders.pdf"))
  #p.dd.prop <- ggplot(subset(abc, (Param!="data" & NumCases > 0 & stoppedEarly =="false")), aes(x = Prop.superspreader, y = densityDependence)) + geom_point(aes(colour = abc.var > alfa), alpha = 0.8)
  #ggplot(subset(abc, (Param!="data" & NumCases > 0 & stoppedEarly =="false")), aes(y = Superspreader, x = ThMean)) + geom_point(aes(colour = abc.var > alfa), alpha = 0.8)
  # Accepted versus rejected parameter sets, by the proportion of superspreaders
  overallMaxDD <- max(subset(abc, (Param!="data" & numDetectableDogs > 0 & stoppedEarly =="false"))$maxDD)
  p.dd.thtd.prop <- ggplot(subset(abc, (Param!="data" & numDetectableDogs > 0 & stoppedEarly =="false")), aes(x = ThMean, y = TdMean)) + geom_point(aes(colour = Acc, size = densityDependence, alpha=Proportion.superspreaders)) +
    annotate(geom = "text",
             x = subset(abc, (Param!="data" & abc.var>alfa))$ThMean,
             y = subset(abc, (Param!="data" & abc.var>alfa))$TdMean,
             label = paste0("maxDD=", subset(abc, (Param!="data" & abc.var>alfa))$maxDD,
                            ", incRate=", sprintf("%1.2f", subset(abc, (Param!="data" & abc.var>alfa))$incursionRate)), size=3)
  ggsave(plot = p.dd.thtd.prop, title = paste0("Proportion of \n", experiment.id, " ", abc.var.str,"\nProportion superspreaders (data) = ", data.prop.superspreader), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_abc_thtd_proportion_superspreaders.pdf"))
  
  # Histogram of the by-run proportion of non-contributors
  data.prop.non.contributors <- abc$numNonContributors[1] / abc$numDetectableDogs[1]
  ###p.dd.nc <- ggplot(subset(abc, (Param!="data" & numDetectableDogs > 0 & stoppedEarly =="false")), aes(x = Proportion.noncontributors)) + geom_histogram(bins=20, aes(fill = abc.var > alfa)) + geom_vline(xintercept = data.prop.non.contributors)
  p.dd.nc <- ggplot(subset(abc, (Param!="data" & numDetectableDogs > 0 & stoppedEarly =="false")), aes(x = Proportion.noncontributors)) + geom_histogram(breaks=seq(0,1, by=0.025), aes(fill = Acc)) + geom_vline(xintercept = data.prop.non.contributors)
  ggsave(plot = p.dd.nc, title = paste0("Proportion of \n", experiment.id, " ", abc.var.str,"\nProportion non-contributors (data) = ", data.prop.non.contributors), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_abc_proportion_noncontributors.pdf"))
  
  # Histogram of the max number of distinct dogs bitten
  data.max.dogs.bitten <- abc$maxDD[1]
  p.dd.mdd <- ggplot(subset(abc, (Param!="data" & numDetectableDogs > 0 & stoppedEarly =="false")), aes(x = maxDD)) + 
    geom_freqpoly(aes(colour = abc.var > alfa)) + 
    geom_vline(xintercept = data.max.dogs.bitten) + geom_vline(xintercept = 2*data.max.dogs.bitten, linetype = 2) + 
    scale_x_continuous(limits=c(0,1000)) + scale_y_log10()
  ggsave(plot = p.dd.mdd, title = paste0(experiment.id, " ", abc.var.str,"\nMax dogs bitten (data) = ", data.max.dogs.bitten), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_abc_max_dogs_bitten.pdf"))
  
  # ----
  
  ddh$abc.var <- abc$abc.var; ddh$densityDependence <- abc$densityDependence
  ddh$ar <- ifelse (ddh$Param == "data", "Data", ifelse(abc$abc.var > alfa, "Accepted", "Rejected"))
  ddhp <- ddh
  ddhp[,1:83] <- ddhp[,1:83] / rowSums(ddhp[,1:83])
  ###ddh$rowSums <- rowSums(ddh[,1:21]); ddh[,1:21] <- ddh[,1:21] / ddh$rowSums
  m.ddh <- melt(ddhp, id.vars = c("Param","ar","abc.var","densityDependence")); m.ddh$variable <- as.numeric(gsub("X", replacement = "", m.ddh$variable)); m.ddh$variable <- ifelse(m.ddh$variable == 10000, 110, m.ddh$variable)
  p.ddh <- ggplot(subset(m.ddh, abc.var > alfa), aes(x=variable, y=value)) + 
    geom_line(aes(group=Param, colour=densityDependence), alpha = 0.2) +
    geom_line(data=subset(m.ddh, Param=="data"), aes(x=variable, y=value), colour = "red") +
    scale_x_continuous(name="Number of distinct dogs bitten") + scale_y_continuous(name = "Relative frequency", limits = c(0,1)) +
    scale_colour_gradient(low = sc.colours$dark.navy, high = sc.colours$orange, limits = c(0,1)) +
    theme_light(); p.ddh
  ggsave(plot = p.ddh, title = paste0("Numbers of distinct dogs bitten\n", experiment.id, " ", abc.var.str,"\nMean accepted R0 = ", meanR0Accept), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_distinctDogs.pdf"))
  
  ddhp$ThShape <- abc$ThShape; ddhp$ThMean <- abc$ThMean; ddhp$TdMean <- abc$TdMean; ddhp$incursionRate <- abc$incursionRate
  m.ddh <- melt(ddhp, id.vars = c("Param","ar","abc.var","densityDependence","ThShape","ThMean","TdMean","incursionRate")); m.ddh$variable <- as.numeric(gsub("X", replacement = "", m.ddh$variable)); m.ddh$variable <- ifelse(m.ddh$variable == 10000, 110, m.ddh$variable)
  p.ddh <- ggplot(subset(m.ddh, abc.var > alfa & Param!="data"), aes(x=variable, y=value)) + geom_line(aes(group=Param, alpha=abc.var, colour=ThShape)) +
    geom_line(data=subset(m.ddh, Param=="data"), aes(x=variable, y=value), colour = "red") +
    scale_x_sqrt(name="Number of distinct dogs bitten") + scale_y_continuous(name = "Relative frequency", limits = c(0,1)) +
    scale_colour_gradient(low = sc.colours$dark.navy, high = sc.colours$orange); p.ddh + theme_classic()
  
  # Plot density histograms
  p.dh1000 <- p.dh(dh = dh1000, abc = abc, ymax = 700, freq = F); p.dh1000
  ggsave(plot = p.dh1000, title = paste0("Relative density\n", experiment.id, " ", abc.var.str,"\nMean accepted R0 = ", meanR0Accept), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_relative_density1000_caseDensity.pdf"))

  # # Plot distribution of distances travelled between cases
  # dist.breaks <- as.numeric(gsub("X", replacement = "", colnames(disth)))
  # dist.breaks <- unique(dist.breaks[!is.na(dist.breaks)])
  # disth$total.num.dists <- rowSums(disth[1:length(dist.breaks)])
  # disth$abc.var <- abc$abc.var; disth$densityDependence <- abc$densityDependence
  # disth$ar <- ifelse (disth$Param == "data", "Data", ifelse(disth$abc.var > alfa, "Accepted", "Rejected"))
  # m.disth <- melt(disth, id.vars = c("Param","ar","abc.var","densityDependence","total.num.dists"));
  # m.disth$variable <- as.numeric(gsub("X", replacement = "", m.disth$variable)) #; m.dhRaw$variable <- ifelse(m.dhRaw$variable == 10000, 110, m.dhRaw$variable)
  # bar.widths <- c(0,dist.breaks[2:length(dist.breaks)] - dist.breaks[1:(length(dist.breaks)-1)])
  # dists.widths <- data.frame(dist.breaks=dist.breaks, bar.widths=bar.widths)
  # match.dist.breaks <- match(m.disth$variable, table=dists.widths$dist.breaks)
  # m.disth$distancesDensity <- 1/dists.widths$bar.widths[match.dist.breaks] * m.disth$value / m.disth$total.num.dists
  # p.disth <- ggplot(subset(m.disth, abc.var > alfa), aes(x=variable, y=distancesDensity)) + geom_line(aes(group=Param, alpha=abc.var, colour=densityDependence)) +
  #   geom_line(data=subset(m.disth, Param=="data"), aes(x=variable, y=distancesDensity), colour = "red") +
  #   scale_x_sqrt("Distance",limits=c(0,10000), breaks=c(0,100,200,300,400,500,600,1000,4000,10000)) + scale_y_sqrt("Relative frequency") +
  #   scale_colour_gradient(low = sc.colours$dark.navy, high = sc.colours$orange, limits = c(0,1)); p.disth
  # ggsave(plot = p.disth, title = paste0("Raw density at case locations\n", experiment.id, " ", abc.var.str,"\nMean accepted R0 = ", meanR0Accept), filename = paste0(ff, experiment.id,"/figs/", model, "_", spatial.scale, "_",abc.var.str,"_distances.pdf"))
  
}

table(abc$Accepted)
summary(subset(abc, Accepted == T)$numDetectableDogs) # Accepted runs well under XXX cases in total
summary(subset(abc, Accepted == T)$R0) # Accepted runs - mean R0 around XXX
summary(subset(abc, Accepted == T)$maxDD) # Accepted runs - max distinct dogs ... goes up to XXX
summary(subset(abc, Accepted == T)$maxDD > max.dd) # Should be zero
summary(subset(abc, Accepted == T)$meanDD) # Mean dogs bitten ~ XXX.XX


